### ISSUE TITLE
Allow to filter for fonts

### ISSUE THREAD

**Issue by MartinMuzatko** [pamelafox/font-previewer-extension#10]
Currently there is no way to search and filter for fonts in the popup.

**Comment by elurie** [comment]
I would love this feature. I am not a coder. but a WordPress design & build person.

**Comment by Chacapamac** [comment]
Yep, that will be great.

**Comment by pamelafox** [comment]
This feature has been implemented and merged. It will be available whenever Chrome approves it.  Thanks @jerboa88 !
